// Fitness App Components
export { default as Dashboard } from './Dashboard.svelte';
export { default as BottomNav } from './BottomNav.svelte';
export { default as RecentWorkouts } from './RecentWorkouts.svelte';
export { default as StrengthChart } from './StrengthChart.svelte';
export { default as WeightChart } from './WeightChart.svelte';
export { default as RestTimer } from './RestTimer.svelte';
export { default as SyncStatus } from './SyncStatus.svelte';
export { default as StreakCalendar } from './StreakCalendar.svelte';
export { default as VolumeTrendChart } from './VolumeTrendChart.svelte';
export { default as MuscleGroupChart } from './MuscleGroupChart.svelte';
export { default as ExerciseDetail } from './ExerciseDetail.svelte';
export { default as ExerciseHistory } from './ExerciseHistory.svelte';
export { default as Calculators } from './Calculators.svelte';
export { default as ExerciseEditor } from './ExerciseEditor.svelte';

// Legacy Property Components (can be removed later)
export { default as PropertyHero } from './PropertyHero.svelte';
export { default as PropertyOverview } from './PropertyOverview.svelte';
export { default as PropertyHighlights } from './PropertyHighlights.svelte';
export { default as PropertyAvailableSpaces } from './PropertyAvailableSpaces.svelte';
export { default as PropertyStats } from './PropertyStats.svelte';
export { default as PropertyGallery } from './PropertyGallery.svelte';
export { default as PropertyProperty } from './PropertyProperty.svelte';
export { default as PropertyLocationSection } from './PropertyLocationSection.svelte';
export { default as PropertyNearby } from './PropertyNearby.svelte';
export { default as PropertyBrochure } from './PropertyBrochure.svelte';
export { default as PropertyRentCalculator } from './PropertyRentCalculator.svelte';
export { default as PropertyLeaseTimeline } from './PropertyLeaseTimeline.svelte';
export { default as PropertyContactSection } from './PropertyContactSection.svelte';
export { default as PropertyFooter } from './PropertyFooter.svelte';
